# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Debug Test

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish this release"
        required: true
        default: false
        type: boolean
      mode:
        description: 'Mode Select'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Debug
        if: ${{ inputs.mode }} == 'debug'
        run: echo ${{ inputs.mode }}
      - name: Release
        if: ${{ inputs.mode }} == 'release'
        run: echo ${{ inputs.mode }}
      - name: Publish
        if: ${{ inputs.publish }}
        run: echo publish